name: Build Dashboard

on:
  workflow_dispatch:
  push:
    branches:
      - html-update

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repo
      uses: actions/checkout@v3
      with:
          token: ${{ secrets.GH_PAT }}

    - name: Setup Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.11'

    - name: Install dependencies
      run: |
        sudo apt-get update
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        sudo apt install -y google-chrome-stable

    - name: Install Chrome
      uses: browser-actions/setup-chrome@v1

    - name: Generate static HTML
      run: python generate_html.py

    - name: Commit updated HTML
      run: |
        git config user.name "github-actions"
        git config user.email "github-actions@github.com"
        git add docs/index.html
        git commit -m "Update static HTML" || echo "No changes to commit"
        git push
