name: Build Dashboard

on:
  workflow_dispatch:
  schedule:
    - cron: "0 * * * *"  # Runs every hour; you can adjust the schedule

permissions:
  contents: write

jobs:
  check-api-update:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Fetch API data
        id: api_check
        run: |
          response=$(curl -s https://fantasy.premierleague.com/api/leagues-h2h-matches/league/2696403/?page=1)
          echo "$response" > current_api_data.json

      - name: Download previous API data artifact (if exists)
        uses: actions/download-artifact@v3
        with:
          name: previous-api-data
          path: ./  # Downloads the artifact to the current directory

      - name: Compare API response
        id: compare_update
        run: |
          # Compare the current API response with the previous response
          if [[ -f previous_api_data.json ]]; then
            if ! diff previous_api_data.json current_api_data.json; then
              echo "API data updated"
              echo "true" >> $GITHUB_ENV  # Set an environment variable indicating an update
              echo "api_updated=true" >> $GITHUB_ENV  # Set output to indicate an update
            else
              echo "API data has not changed."
              echo "api_updated=false" >> $GITHUB_ENV  # No update
            fi
          fi
          # Store the current API data for future comparisons
          mv current_api_data.json previous_api_data.json
          
      - name: Upload updated previous API data as artifact
        uses: actions/upload-artifact@v3
        with:
          name: previous-api-data
          path: previous_api_data.json

    outputs:
      api_updated: ${{ steps.compare_update.outputs.api_updated }}

  build:
    runs-on: ubuntu-latest
    needs: check-api-update  # Ensures this job runs after `check-api-update` job

    # This ensures the build job only runs if the API data has changed or if the workflow is manually triggered
    if: ${{ needs.check-api-update.outputs.api_updated == 'true' || github.event_name == 'workflow_dispatch' }}

    steps:
    - name: Checkout repo
      uses: actions/checkout@v3
      with:
          token: ${{ secrets.GH_PAT }}

    - name: Setup Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.11'

    - name: Install dependencies
      run: |
        sudo apt-get update
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Install Chrome
      uses: browser-actions/setup-chrome@v1
    
    - name: Setup git for commit
      run: |
        git config user.name "github-actions"
        git config user.email "github-actions@github.com"
    
    - name: Checkout and reset html-update branch
      run: |
        git fetch --all
        git checkout html-update || git checkout -b html-update origin/html-update  # Create the html-update branch if it doesn't exist
        git reset --hard origin/main  # Reset the html-update branch to match the main branch

    - name: Generate static HTML
      run: |
        python generate_html.py
        cat app.py

    - name: Generate static HTML and commit changes
      run: |
        git add .  # Stage the generated index.html
        git commit -m "Update static HTML" || echo "No changes to commit"  # Commit changes if any

    - name: Push to html-update branch
      run: |
        git push origin html-update --force # Push the updated file to html-update branch with force option (to overwrite history because of rebase)
