name: Build Dashboard

on:
  workflow_dispatch:

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repo
      uses: actions/checkout@v3
      with:
          token: ${{ secrets.GH_PAT }}

    - name: Setup Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.11'

    - name: Install dependencies
      run: |
        sudo apt-get update
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        sudo apt install -y google-chrome-stable

    - name: Install Chrome
      uses: browser-actions/setup-chrome@v1

    - name: Generate static HTML
      run: python generate_html.py
    
    - name: Setup git for commit
      run: |
        git config user.name "github-actions"
        git config user.email "github-actions@github.com"

    - name: Stash local changes before switching branches
      run: |
        git add docs/index.html  # Stage only the changed file
        git stash push -m "Stashing changes before switching to html-update branch"  # Stash the changes
  
    - name: Check out and create html-update branch if not exists
      run: |
        git fetch origin
        git checkout html-update || git checkout -b html-update
        git pull origin html-update

    - name: Apply stashed changes and commit
      run: |
        git stash pop  # Apply the stashed changes (docs/index.html)
        git checkout --theirs docs/index.html  # Resolve the conflict by taking the changes from the stash (i.e., "theirs")
        git add docs/index.html  # Add the stashed file changes
        git commit -m "Update static HTML" || echo "No changes to commit"  # Only commit if there are changes
    
    - name: Push to html-update branch
      run: |
        git push origin html-update  # Push the updated file to html-update branch
  
