name: Build Dashboard

on:
  workflow_dispatch:

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repo
      uses: actions/checkout@v3
      with:
          token: ${{ secrets.GH_PAT }}

    - name: Setup Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.11'

    - name: Install dependencies
      run: |
        sudo apt-get update
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        sudo apt install -y google-chrome-stable

    - name: Install Chrome
      uses: browser-actions/setup-chrome@v1

    - name: Generate static HTML
      run: python generate_html.py
    
    - name: Setup git for commit
      run: |
        git config user.name "github-actions"
        git config user.email "github-actions@github.com"

    - name: Check out and create html-update branch if not exists
      run: |
        git fetch origin
        git checkout html-update || git checkout -b html-update
        git pull origin html-update

    - name: Copy updated docs/index.html to html-update branch
      run: |
        git checkout main -- docs/index.html  # Checkout only the updated file from main branch
        git add docs/index.html
        git commit -m "Update static HTML" || echo "No changes to commit"  # Only commit if changes exist
    
    - name: Push to html-update branch
      run: |
        git push origin html-update  # Push the updated file to html-update branch
  
