name: Build Dashboard

on:
  workflow_dispatch:

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repo
      uses: actions/checkout@v3
      with:
          token: ${{ secrets.GH_PAT }}

    - name: Setup Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.11'

    - name: Install dependencies
      run: |
        sudo apt-get update
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Install Chrome
      uses: browser-actions/setup-chrome@v1
    
    - name: Setup git for commit
      run: |
        git config user.name "github-actions"
        git config user.email "github-actions@github.com"

    - name: Checkout and rebase html-update branch onto main
      run: |
        git fetch origin
        git checkout html-update  # Checkout the html-update branch
        git stash
        git rebase origin/main  || git rebase --strategy=recursive --strategy-option=theirs # Rebase onto the latest main with conflict resolution overwrite

    - name: Generate static HTML
      run: python generate_html.py

    - name: Generate static HTML and commit changes
      run: |
        git add docs/index.html  # Stage the generated index.html
        git commit -m "Update static HTML" || echo "No changes to commit"  # Commit changes if any

    - name: Push to html-update branch
      run: |
        git push origin html-update  # Push the updated file to html-update branch
  
