name: Build Dashboard

on:
  workflow_dispatch:

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repo
      uses: actions/checkout@v3
      with:
          token: ${{ secrets.GH_PAT }}

    - name: Setup Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.11'

    - name: Install dependencies
      run: |
        sudo apt-get update
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Install Chrome
      uses: browser-actions/setup-chrome@v1
    
    - name: Setup git for commit
      run: |
        git config user.name "github-actions"
        git config user.email "github-actions@github.com"
    
    - name: Clean up rebase state (if exists)
      run: |
        rm -rf .git/rebase-merge
        git rebase --abort || echo "No rebase in progress"

    - name: Checkout and rebase html-update branch onto main
      run: |
        git checkout html-update  # Checkout the html-update branch
        git fetch origin
        git reset --hard origin/main  # Reset the html-update branch to match the main branch

    - name: Generate static HTML
      run: |
        python generate_html.py
        cat app.py

    - name: Generate static HTML and commit changes
      run: |
        git add .  # Stage the generated index.html
        git commit -m "Update static HTML" || echo "No changes to commit"  # Commit changes if any

    - name: Push to html-update branch
      run: |
        git push origin html-update --force # Push the updated file to html-update branch with force option (to overwrite history beacuse of rebase)
  
